spring.application.name=back

spring.datasource.url=jdbc:mariadb://localhost:3306/NoteFrais
spring.datasource.username=root
spring.datasource.password=zosefa
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

upload.dir=uploads/

server.port=8081


